"""HARD TIME COMPONENTS STATUS REPORT -- scanned "sandwich" PDF (a raster
page image with an old, low-quality OCR text layer baked in underneath),
needs a fresh per-column-strip OCR pass end to end; the file's own baked-in
text layer is unusable for row data.

Confirmed directly on a real corpus file (4 pages): `page.rects`/
`page.lines`/`page.curves` are all empty on every page and `page.images`
holds exactly one full-page raster image per page -- the ruled grid visible
when the page is rendered is part of that raster image, not vector-drawn,
so `extract_tables()` returns nothing (unlike this package's other
ruled-table HT variants, e.g. `mpd_service_interval_status.py`, which read
a genuine vector-drawn grid via `extract_tables()` directly).

`page.extract_text()` is NOT blank (over 1000 characters per page, so the
router's own generic "blank text -> OCR fallback" check never fires), but
the words are badly scrambled at the character level -- e.g. "PACK BYPASS
VALVE/TRIM AIR MODUL VLV" decodes as "pacbkypavsaslve/triamirmoduvllv".
Confirmed directly this is NOT a broken font/glyph-mapping issue (unlike
`hard_time_aircraft_components_status_broken_font.py`'s own file): reading
`page.chars` directly shows every individual character decodes correctly
with a plain `Helvetica` font and correct per-character Unicode text --
only whole-word ordering/spacing is wrong. Cross-checking column
position against a clean rendered-image reading of the same file confirms
the actual page content is an old, independently-OCR'd text layer of
middling quality (baked into the PDF at some prior processing step, not
generated by pdfplumber) -- it merges adjacent words with no space,
sporadically drops or misreads individual characters (e.g. this file's own
"Partno"/"Pos."/"Inst-Date" column headers decode as "panno"/"p05."/
"inn-date"), and is therefore not trustworthy for exact PART_NUMBER/
SERIAL_NUMBER/date values even where a human reader could visually
resolve the correct value from the same misread text. So this variant
ignores that text layer entirely (it is useful only as the plain-text
SIGNATURES anchor below, where the exact phrase happens to decode cleanly)
and instead re-derives every field from a fresh render + OCR pass, per
this project's per-column-strip-OCR convention for a file whose whole-page/
whole-row OCR would otherwise be unreliable.

Header block (repeats near-identically on every page, upper-left corner)::

    Date   <report date>
    TAH    <total aircraft hours>
    TAC    <total aircraft cycles>

...and, centered/right on the same header band::

    MSN <msn> HARD TIME COMPONENTS STATUS REPORT      <operator wordmark>

Confirmed directly: a tight per-line crop (not a single whole-header OCR
pass, which mis-reads on some pages) around each of these three lines,
upscaled 2x-3x, OCRs cleanly and identically across all 4 pages of the
sample file. Parsed once per page and kept the first time every field is
non-empty (mirrors this package's usual header-metadata convention), since
a page's own header crop occasionally fails where an earlier page's
succeeded.

Main table, one ruled header row (part of the page's own raster image, not
extractable text), 20 columns::

    ATA | Partno | Serialno | Description | Pos. | Inst-Date | TASK CARD |
    TASK | INTERVAL{DAY,FHR,CYC} | LAST DONE{DAY,FHR,CYC} |
    NEXT DUE{DATE,FHR,CYC} | REMAINING{DAY,FHR,CYC}

Column X-boundaries below are expressed as fractions of the rendered page's
own width (confirmed directly via a numpy column-darkness scan for the
ruled grid's own vertical divider lines on page 1, at 300 DPI) rather than
fixed pixel offsets -- this file's own 4 pages render at two very slightly
different physical widths (831.36pt vs 829.44pt, under 0.3%), so a
fraction-of-width scheme keeps every column's own crop aligned on every
page without needing a per-page recalibration pass.

Row anchoring: TASK_CARD is used as the per-row Y anchor (a short
digit-and-dash token, e.g. "21-51-10-001", present on very nearly every
real data row -- including a component's own second/third scheduled-task
row, which repeats PART_NUMBER/SERIAL_NUMBER/DESCRIPTION/POSITION/
INSTALLED_DATE as blank cells but always carries its own TASK_CARD and
TASK). This is a deliberately different anchor choice than this package's
other per-column-strip HT variant (`hard_time_aircraft_components_status_
broken_font.py`'s own ATA-column anchor) -- confirmed directly on this
file's own sample that the ATA column is far too sparse (it holds a bare
chapter code only on the first row of a new ATA chapter, blank on every
other row) and, worse, unreliable even where present: a single whole-column
OCR pass drops or mis-segments an isolated 2-digit code surrounded by nine
blank rows above and below it in a way a dense, virtually-every-row column
like TASK_CARD does not suffer from. Rather than guess at a fix for that
column's own OCR reliability, ATA is captured on a best-effort basis only
(whatever a bare whole-column OCR pass finds, filtered to a plausible
chapter-code range) and is NOT forward-filled from the previous row --
unlike PART_NUMBER/SERIAL_NUMBER/DESCRIPTION/POSITION/INSTALLED_DATE below,
which anchor reliably enough to forward-fill with confidence, a
best-effort-only ATA reading that turned out wrong would silently
mis-attribute an entire chapter's worth of rows to the wrong ATA if forward-
filled; left blank-or-detected instead, this is a visibly incomplete field
rather than a confidently wrong one (`sheet_types/ht.py`'s own
`normalize_and_validate()` does not call `shared.cleanup.forward_fill_ata`
the way `occm.py` does, so this is a deliberate per-variant choice, not a
gap the router papers over).

Row grain: a tracked component instance is usually one physical row, but
PART_NUMBER/SERIAL_NUMBER/DESCRIPTION/POSITION/INSTALLED_DATE come back
blank on a second (or third) row directly below when that row is a second
scheduled task under the very same physical unit (same PN/SN, a new
TASK_CARD of its own, e.g. a battery's own "PARTIAL OVERHAUL" line and its
own sibling "OVERHAUL, OR PERFORM ALL RELEVANT CMM" line). These are
reconstructed with a single forward-fill pass, independently per field,
NOT reset per page (confirmed directly on the sample file: unlike
`mpd_service_interval_status.py`'s own file, this file's own chapter/
component runs do cross a page boundary without repeating the PN/SN/
description on the new page's own first row).

Numeric/date cells (INTERVAL/LAST DONE/NEXT DUE/REMAINING) sit behind the
same dotted leader-line styling used throughout this ruled grid; a
column's own OCR pass frequently picks up the leader dots and stray ruled-
border pixels as junk tokens (e.g. ":", "|", ";", or a short garbled run).
Rather than pass these through or try to character-map-correct them, each
of these columns is reduced to only its own digit-and-punctuation
substrings (a plain `\d[\d,]+` scan across the column's raw OCR tokens,
`\d{1,2}[.\-]\d{1,2}[.\-]\d{2,4}` for the one date-shaped column) and
non-numeric noise is dropped outright -- per this project's "never guess a
wrong split" convention, a dropped stray artifact is preferred over a
confidently-wrong merged value. LAST_DONE_DAY is a partial exception: this
file's own real rows put either a bare day-count integer OR a full
calendar date in that same ruled cell (confirmed directly, e.g. a battery's
"PARTIAL OVERHAUL" row leaves it blank while its own sibling "OVERHAUL, OR
PERFORM ALL RELEVANT CMM" row on the very same physical component carries a
real date there) -- so this column accepts either shape rather than forcing
one.
"""
from __future__ import annotations
import re

from PIL import Image

from sheet_types.ht_variants._base import merged_rules
from shared.ocr_bridge import render_page, ocr_words, ocr_text, page_count

NAME = "Hard Time Day/FHR/Cyc Matrix (Scanned)"

# This exact phrase decodes cleanly through the file's own otherwise badly
# scrambled baked-in OCR text layer (see module docstring) -- confirmed
# directly: page 1's own `extract_text()` output contains
# "...msn <digits>hard time components status report" verbatim, i.e. the
# contiguous substring "hard time components status report" (the MSN
# digit run right before "hard" is merged with no space, but everything
# from "hard" onward reads clean). Checked against every SIGNATURES list in
# occm.py/ht.py/llp.py and every occm_variants/ht_variants/llp_variants
# module's own SIGNATURES list (including a plain grep for "COMPONENTS
# STATUS REPORT" and "HARD TIME COMPONENTS"); no collision found -- the
# nearest look-alikes are georgian_airways_ht_components_status.py's own
# "HARD TIME COMPONENTS STATUS FOR A/C-REGISTRATION" and
# hard_time_status_mpd_cert_fin.py's file (whose own SIGNATURES are
# unrelated short fragments, "MPD Item #"/"LAST INSP/OVH" -- see that
# module's own docstring, which explicitly avoided the bare "HARD TIME
# COMPONENTS STATUS" phrase for this same collision-avoidance reason); this
# variant's own longer phrase, with the trailing "REPORT", is not a
# substring of either in either direction.
SIGNATURES = [
    "HARD TIME COMPONENTS STATUS REPORT",
]

CANONICAL_COLUMNS = [
    "ATA",
    "PART_NUMBER",
    "SERIAL_NUMBER",
    "DESCRIPTION",
    "POSITION",
    "INSTALLED_DATE",
    "TASK_CARD",
    "TASK",
    "INTERVAL_DAY",
    "INTERVAL_FHR",
    "INTERVAL_CYC",
    "LAST_DONE_DAY",
    "LAST_DONE_FHR",
    "LAST_DONE_CYC",
    "NEXT_DUE_DATE",
    "NEXT_DUE_FHR",
    "NEXT_DUE_CYC",
    "REMAINING_DAY",
    "REMAINING_FHR",
    "REMAINING_CYC",
    # Header metadata -- same on every page of a given file, stamped on
    # every row.
    "OPERATOR",
    "MSN",
    "REPORT_DATE",
    "TAH",
    "TAC",
]

_DATE_RE = r"^\d{1,2}[.\-]\d{1,2}[.\-]\d{2,4}$"
_NUM_RE = r"^-?[\d,]+$"
_DAY_OR_DATE_RE = rf"^(?:-?[\d,]+|\d{{1,2}}[.\-]\d{{1,2}}[.\-]\d{{2,4}})$"

_OVERRIDES = {
    # This file leaves ATA blank on almost every row by source convention
    # (see module docstring) and it is captured best-effort only, never
    # forward-filled -- allow_empty rather than a hard requirement.
    "ATA": {"allow_empty": True},
    "POSITION": {"allow_empty": True},
    "INSTALLED_DATE": {"pattern": _DATE_RE + "|^TBD$", "allow_empty": True},
    "TASK_CARD": {"pattern": r"^[\dA-Za-z][\dA-Za-z\-\s]*$", "allow_empty": True},
    "TASK": {"allow_empty": True},
    "INTERVAL_DAY": {"pattern": _NUM_RE, "allow_empty": True},
    "INTERVAL_FHR": {"pattern": _NUM_RE, "allow_empty": True},
    "INTERVAL_CYC": {"pattern": _NUM_RE, "allow_empty": True},
    "LAST_DONE_DAY": {"pattern": _DAY_OR_DATE_RE, "allow_empty": True},
    "LAST_DONE_FHR": {"pattern": _NUM_RE, "allow_empty": True},
    "LAST_DONE_CYC": {"pattern": _NUM_RE, "allow_empty": True},
    "NEXT_DUE_DATE": {"pattern": _DATE_RE, "allow_empty": True},
    "NEXT_DUE_FHR": {"pattern": _NUM_RE, "allow_empty": True},
    "NEXT_DUE_CYC": {"pattern": _NUM_RE, "allow_empty": True},
    "REMAINING_DAY": {"pattern": _NUM_RE, "allow_empty": True},
    "REMAINING_FHR": {"pattern": _NUM_RE, "allow_empty": True},
    "REMAINING_CYC": {"pattern": _NUM_RE, "allow_empty": True},
    # Header metadata -- a single OCR misread here shouldn't flag every
    # row of the file, same reasoning this package's other header-plus-body
    # OCR variants use.
    "OPERATOR": {"allow_empty": True},
    "MSN": {"allow_empty": True},
    "REPORT_DATE": {"allow_empty": True},
    "TAH": {"allow_empty": True},
    "TAC": {"allow_empty": True},
}
RULES = merged_rules(_OVERRIDES)

# Column X-boundaries, as a fraction of the rendered page's own width (see
# module docstring for why fractions rather than fixed pixels) -- derived
# directly from a numpy column-darkness scan of page 1's own ruled grid at
# 300 DPI, confirmed stable against a visual check of pages 1 and 4 (whose
# own physical page width differs by <0.3%).
_COLUMNS = [
    (0.00520, 0.02483, "ATA"),
    (0.02483, 0.08604, "PART_NUMBER"),
    (0.08604, 0.14665, "SERIAL_NUMBER"),
    (0.14665, 0.32245, "DESCRIPTION"),
    (0.32245, 0.36835, "POSITION"),
    (0.36835, 0.42047, "INSTALLED_DATE"),
    (0.42047, 0.47600, "TASK_CARD"),
    (0.47600, 0.63216, "TASK"),
    (0.63216, 0.65473, "INTERVAL_DAY"),
    (0.65473, 0.68130, "INTERVAL_FHR"),
    (0.68130, 0.69863, "INTERVAL_CYC"),
    (0.69863, 0.74221, "LAST_DONE_DAY"),
    (0.74221, 0.78581, "LAST_DONE_FHR"),
    (0.78581, 0.80312, "LAST_DONE_CYC"),
    (0.80312, 0.84642, "NEXT_DUE_DATE"),
    (0.84642, 0.87241, "NEXT_DUE_FHR"),
    (0.87241, 0.88972, "NEXT_DUE_CYC"),
    (0.88972, 0.91127, "REMAINING_DAY"),
    (0.91127, 0.93736, "REMAINING_FHR"),
    (0.93736, 0.95468, "REMAINING_CYC"),
]
# Columns joined with a single space when a cell's OCR breaks into more
# than one word token (genuine multi-word free text or a PN/description
# with an internal space); every other column's tokens are numeric/code
# fragments joined with no separator ambiguity concerns (handled by
# `_clean_numeric`/`_clean_date` instead, see below).
_JOIN_SPACE = {"DESCRIPTION", "TASK", "PART_NUMBER", "POSITION"}

_NUMERIC_COLS = {
    "INTERVAL_DAY", "INTERVAL_FHR", "INTERVAL_CYC",
    "LAST_DONE_FHR", "LAST_DONE_CYC",
    "NEXT_DUE_FHR", "NEXT_DUE_CYC",
    "REMAINING_DAY", "REMAINING_FHR", "REMAINING_CYC",
}
# Accepts either a bare integer or a calendar date in the same cell (see
# module docstring).
_DAY_OR_DATE_COLS = {"LAST_DONE_DAY"}
_DATE_COLS = {"NEXT_DUE_DATE"}

_NUM_TOKEN_RE = re.compile(r"-?[\d,]{2,}")
_DATE_TOKEN_RE = re.compile(r"\d{1,2}[.\-]\d{1,2}[.\-]\d{2,4}")

# Columns that are short alnum "codes" (PN/SN/task-card refs, not free
# text) -- stray leading/trailing OCR noise chars (a stray "_", a smart
# quote, an errant leading "-" picked up from a neighbouring dotted leader
# line) are stripped from the joined value's own ends rather than passed
# through, per this project's usual "strip an unrecoverable artifact
# outright rather than guess it into a real character" convention (see
# e.g. `hard_time_aircraft_components_status_broken_font.py`'s own
# `_ARTIFACT_CHAR_RE`). Confirmed directly this does not clip real PN/SN
# content on the sample file -- every real PN/SN in this file starts and
# ends with an alphanumeric character.
_CODE_COLS = {"PART_NUMBER", "SERIAL_NUMBER", "TASK_CARD", "ATA"}
_CODE_STRIP_CHARS = " _\"'`‘’“”.,;:()[]{}|~"

# Row anchor: a short digit-and-dash task-card code, e.g. "21-51-10-001",
# "24-31-01-00", "25-21-01-0XM" (loose enough to also catch a wrapped
# second line's own truncated OCR reading, e.g. "6205-001" for a genuine
# "21-62-05-001" -- see module docstring; the anchor only needs a stable Y
# position, not a perfectly-decoded value).
_ANCHOR_RE = re.compile(r"^[\dA-Za-z]{1,4}-[\dA-Za-z-]{1,10}$")
_ATA_TOKEN_RE = re.compile(r"^\d{2}$")
_ATA_MIN, _ATA_MAX = 20, 83

# Y-tolerance for bucketing a non-anchor column's word to its nearest
# TASK_CARD anchor -- measured directly against this file's own row pitch
# (~32.5px @ 300 DPI between consecutive rows); comfortably under half
# that, to avoid bleeding a neighbouring row's own value into this one.
_ANCHOR_TOLERANCE_PX = 14

_FILLABLE = ("PART_NUMBER", "SERIAL_NUMBER", "DESCRIPTION", "POSITION",
             "INSTALLED_DATE")

_HEADER_FIELDS = ["OPERATOR", "MSN", "REPORT_DATE", "TAH", "TAC"]

_DATE_HDR_RE = re.compile(r"Date\s+(\S+)", re.IGNORECASE)
_TAH_RE = re.compile(r"TAH\s+(\S+)", re.IGNORECASE)
_TAC_RE = re.compile(r"TAC\s+(\S+)", re.IGNORECASE)
_MSN_RE = re.compile(r"MSN\s+(\S+)", re.IGNORECASE)


def _col_bounds(w: int, name: str) -> tuple[int, int]:
    for lo, hi, col in _COLUMNS:
        if col == name:
            return int(lo * w), int(hi * w)
    raise KeyError(name)


async def _ocr_column(img, name: str, y0: int, y1: int, scale: int = 2) -> list[tuple[float, str]]:
    """OCR one column's full-height strip and return (top, text) pairs in
    original-image page coordinates."""
    x0, x1 = _col_bounds(img.width, name)
    crop = img.crop((x0, y0, x1, y1))
    if scale != 1:
        crop = crop.resize((crop.width * scale, crop.height * scale), Image.LANCZOS)
    words = await ocr_words(crop, psm=6, min_conf=-1)
    out = []
    for w in words:
        text = str(w.get("text", "")).strip()
        if not text:
            continue
        out.append((y0 + w["top"] / scale, text))
    return out


def _best_numeric(found: list[str]) -> str:
    """A ruled numeric cell holds exactly one value; multiple digit-group
    matches from one anchor's own OCR tokens are either (a) the same value
    read twice (adjacent word-boxes for one printed number) or (b) a short
    noise fragment (a stray leader-dot run OCR'd as 1-2 digits) alongside
    the real, longer reading. Deduping exact repeats and then keeping the
    longest remaining match handles both without guessing at a merge."""
    seen = list(dict.fromkeys(found))  # dedupe, preserve order
    if not seen:
        return ""
    return max(seen, key=len)


def _clean_field(name: str, tokens: list[str]) -> str:
    if name in _NUMERIC_COLS:
        found: list[str] = []
        for t in tokens:
            found.extend(_NUM_TOKEN_RE.findall(t))
        return _best_numeric(found)
    if name in _DATE_COLS:
        found = []
        for t in tokens:
            found.extend(_DATE_TOKEN_RE.findall(t))
        found = list(dict.fromkeys(found))
        return " ".join(found)
    if name in _DAY_OR_DATE_COLS:
        found = []
        for t in tokens:
            found.extend(_DATE_TOKEN_RE.findall(t))
            if not _DATE_TOKEN_RE.search(t):
                found.extend(_NUM_TOKEN_RE.findall(t))
        found = list(dict.fromkeys(found))
        if len(found) > 1:
            return _best_numeric(found)
        return " ".join(found)
    sep = " " if name in _JOIN_SPACE else ""
    text = sep.join(tokens)
    if name in _CODE_COLS:
        text = text.strip(_CODE_STRIP_CHARS)
    return text


async def _parse_header(img) -> dict:
    """Per-line crop + OCR of the Date/TAH/TAC block and the MSN/title/
    operator band -- see module docstring for why a single whole-header
    OCR pass isn't used (unreliable on some pages of the sample file)."""
    meta = {k: "" for k in _HEADER_FIELDS}
    w = img.width

    async def line(y0: int, y1: int, x0: int, x1: int, psm: int = 6) -> str:
        crop = img.crop((x0, y0, x1, y1))
        crop = crop.resize((crop.width * 3, crop.height * 3), Image.LANCZOS)
        return (await ocr_text(crop, psm=psm)).strip()

    block = await line(50, 220, 0, min(520, w))
    m = _DATE_HDR_RE.search(block)
    if m:
        meta["REPORT_DATE"] = m.group(1)
    m = _TAH_RE.search(block)
    if m:
        meta["TAH"] = m.group(1)
    m = _TAC_RE.search(block)
    if m:
        meta["TAC"] = m.group(1)

    title = await line(100, 190, int(w * 0.24), int(w * 0.62))
    m = _MSN_RE.search(title)
    if m:
        meta["MSN"] = m.group(1)

    operator = await line(30, 130, int(w * 0.62), w)
    operator = " ".join(operator.split())
    if operator:
        meta["OPERATOR"] = operator

    return meta


async def ocr_detect(pdf_path: str) -> bool:
    """Cheap page-1 OCR check for the router's blank-text fallback. Not
    expected to fire for the known source file (its baked-in text layer is
    never blank -- it's found via plain-text SIGNATURES instead, see module
    docstring), kept for interface consistency and in case a more severely
    degraded copy of this template turns up with no usable text layer at
    all."""
    try:
        img = await render_page(pdf_path, 0, dpi=300)
        w = img.width
        crop = img.crop((int(w * 0.24), 100, int(w * 0.62), 190))
        crop = crop.resize((crop.width * 2, crop.height * 2), Image.LANCZOS)
        text = (await ocr_text(crop, psm=6)).upper()
        return "HARD TIME COMPONENTS STATUS REPORT" in text
    except Exception:
        return False


async def extract(pdf_path: str) -> list[dict]:
    records: list[dict] = []
    header_meta = {k: "" for k in _HEADER_FIELDS}
    n_pages = await page_count(pdf_path)

    for page_index in range(n_pages):
        img = await render_page(pdf_path, page_index, dpi=300)
        h = img.height

        if not all(header_meta.values()):
            page_meta = await _parse_header(img)
            for k, v in page_meta.items():
                if v and not header_meta[k]:
                    header_meta[k] = v

        col_words: dict[str, list[tuple[float, str]]] = {}
        for _, _, name in _COLUMNS:
            col_words[name] = await _ocr_column(img, name, 260, h)

        anchors = sorted(
            top for top, text in col_words["TASK_CARD"]
            if _ANCHOR_RE.match(text)
        )

        cur = {f: "" for f in _FILLABLE}
        for atop in anchors:
            row: dict[str, str] = {}
            for _, _, name in _COLUMNS:
                if name == "TASK_CARD":
                    continue
                toks = [text for top, text in col_words[name]
                        if abs(top - atop) <= _ANCHOR_TOLERANCE_PX]
                row[name] = _clean_field(name, toks)

            tc_toks = [text for top, text in col_words["TASK_CARD"]
                       if abs(top - atop) <= _ANCHOR_TOLERANCE_PX]
            row["TASK_CARD"] = " ".join(tc_toks).strip(_CODE_STRIP_CHARS)

            # ATA: best-effort only, never forward-filled (see module
            # docstring).
            if not _ATA_TOKEN_RE.match(row.get("ATA", "")):
                row["ATA"] = ""

            for f in _FILLABLE:
                if row[f]:
                    cur[f] = row[f]
                else:
                    row[f] = cur[f]

            row["_page"] = page_index + 1
            row.update(header_meta)
            records.append(row)

    return records
