"""STARS / Trax MIS — "A/C Detail Items Print" HT report.

Generated by the STARS / Trax maintenance system; identified by the
`A/C Detail Items Print` header on page 1. Two sub-layouts in the corpus:

  * **Air Astana / Sunwing style** (P4-NAS, P4-OAS, MSN 28651):
    Column order is `... S/N Position Category Mnt/Ctl ...`. The
    description line carries an `Install Date:` marker, giving a clean
    line-pair anchor.

  * **MX (XA-) / B737-NG style** (2666, 2780, 32404, A306):
    Column order is swapped to `... S/N Category Position Mnt/Ctl ...`
    and there is no `Install Date:` marker — the description sits alone
    on its own line.

Both share the `HT` Mnt/Ctl token immediately after the position/category
pair, so we anchor on the `HT` literal rather than the date marker, and
use the column-header line on the page to learn whether Position comes
before or after Category for this file.

ATA and PN are forward-filled — a row without a leading ATA-dash token
belongs to the previous ATA, and a row whose first token isn't PN-shaped
inherits the PN from the previous record.
"""
from __future__ import annotations
import re
import pdfplumber

from sheet_types.occm_variants._base import merged_rules

NAME = "STARS Trax HT"
SIGNATURES = [
    "A/C Detail Items Print",
]
CANONICAL_COLUMNS = [
    "ATA",
    "PART_NUMBER",
    "SERIAL_NUMBER",
    "POSITION",
    "DESCRIPTION",
    "CATEGORY",
    "INSTALL_DATE",
]
_OVERRIDES = {
    "ATA":          {"pattern": r"^\d{1,2}(-\d{1,3})*$", "allow_empty": True},
    "POSITION":     {"pattern": r"^[A-Z0-9/_-]{1,12}$", "uppercase": True,
                     "allow_empty": True},
    "INSTALL_DATE": {"pattern": r"^\d{1,2}[\./]\d{1,2}[\./]\d{2,4}$",
                     "allow_empty": True},
    "CATEGORY":     {"allow_empty": True},
    "SERIAL_NUMBER": {"allow_empty": True},
}
RULES = merged_rules(_OVERRIDES)

_ATA_RE = re.compile(r"^\d{1,2}-\d{1,3}-\d{1,2}$")
# PN-shape: has at least one letter AND one digit, length >= 4. Filters
# out FIN tokens like `6HL` (no internal dash and shorter than 4 chars
# in some forms) — but also accepts `9024-15704-2`, `VFT210A1`, etc.
_PN_LIKELY = re.compile(r"^(?=[A-Z0-9/_-]*[A-Z])(?=[A-Z0-9/_-]*\d)[A-Z0-9/_-]{5,}$")
_DATE_RE = re.compile(r"\b(\d{1,2}[\./]\d{1,2}[\./]\d{2,4})\b")
_HEADER_SKIP = re.compile(
    r"Print Date|A/C Detail|^Page:|^A/C:\s|Type/Series|Scheduled\s+Actuals|"
    r"Times As Of", re.I)
# Column-header line tells us the position/category column order.
_HEADER_COLS = re.compile(r"ATA\s+P/N.*S/N\s+(Position|Category)\s+(Position|Category)",
                          re.I)
# Known CATEGORY tokens we see in the corpus (used to disambiguate when
# the header line wasn't captured).
_CATEGORY_TOKENS = {
    "RESTORE", "RST", "RPLBAT", "RPL", "INSPECT", "TSINSP", "TSO", "OVH",
    "OVERHAUL", "CHECK", "CK1", "CK2", "CK3", "TEST", "DISCARD",
    "REPLACE", "TC", "LL", "FNC", "CLEAN", "FROM", "AC",
}


def extract(pdf_path: str) -> list[dict]:
    records: list[dict] = []
    with pdfplumber.open(pdf_path) as pdf:
        for page_num, page in enumerate(pdf.pages, start=1):
            text = page.extract_text() or ""
            if len(text) < 80:
                continue
            lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
            # Learn column order from header if present on this page.
            pos_first = True  # default Air Astana / Sunwing style
            for ln in lines[:20]:
                m = _HEADER_COLS.search(ln)
                if m:
                    pos_first = (m.group(1).lower() == "position")
                    break
            cur_ata = ""
            cur_pn = ""
            i = 0
            while i < len(lines):
                ln = lines[i]
                if _HEADER_SKIP.search(ln):
                    i += 1; continue
                toks = ln.split()
                if not toks:
                    i += 1; continue
                # Skip the column-header itself.
                if toks[0].upper() == "ATA" and "P/N" in ln:
                    i += 1; continue
                # ATA-dash leading token?
                ti = 0
                if _ATA_RE.match(toks[0]):
                    cur_ata = toks[0]
                    ti = 1
                if ti >= len(toks):
                    i += 1; continue
                # PN-shape leading token? (after ATA)
                if _PN_LIKELY.match(toks[ti]):
                    cur_pn = toks[ti]
                    ti += 1
                if ti + 2 >= len(toks):
                    i += 1; continue
                sn = toks[ti]
                # Next two tokens are Position + Category in column-header order.
                t1 = toks[ti + 1]
                t2 = toks[ti + 2]
                if pos_first:
                    position, category = t1, t2
                else:
                    position, category = t2, t1
                # Heuristic correction: if t1/t2 layout disagrees with what
                # CATEGORY_TOKENS knows, prefer the dictionary signal.
                if t1.upper() in _CATEGORY_TOKENS and t2.upper() not in _CATEGORY_TOKENS:
                    category, position = t1, t2
                elif t2.upper() in _CATEGORY_TOKENS and t1.upper() not in _CATEGORY_TOKENS:
                    position, category = t1, t2
                # Description: next non-skip line that isn't another record.
                desc = ""
                install_date = ""
                if i + 1 < len(lines):
                    next_ln = lines[i + 1]
                    if "Install Date:" in next_ln:
                        m = _DATE_RE.search(next_ln)
                        if m: install_date = m.group(1)
                        idx = next_ln.find("Install Date:")
                        desc = next_ln[:idx].strip()
                        i += 2
                    else:
                        # Plain description line (XA-/2666 style)
                        nt = next_ln.split()
                        looks_like_anchor = (
                            (nt and (_ATA_RE.match(nt[0]) or _PN_LIKELY.match(nt[0])))
                            or _HEADER_SKIP.search(next_ln)
                        )
                        if not looks_like_anchor:
                            desc = next_ln
                            i += 2
                        else:
                            i += 1
                else:
                    i += 1
                if not (cur_pn and sn):
                    continue
                records.append({
                    "ATA": cur_ata.split("-")[0] if cur_ata else "",
                    "PART_NUMBER": cur_pn,
                    "SERIAL_NUMBER": sn,
                    "POSITION": position,
                    "DESCRIPTION": desc,
                    "CATEGORY": category,
                    "INSTALL_DATE": install_date,
                    "_page": page_num,
                })
    return records
